### ISSUE TITLE
No output on serial port

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/oob-mbed-os-example-wifi#10]
Compiled latest version with ARM and GCC
SHA: 866e786419019d14930857bc71eb067cbce6cd29

No messages shown on serial port (configured as 9600 bauds)

@andreaslarssonublox @bulislaw @0xc0170

**Comment by andreaslarssonublox** [comment]
@MarceloSalazar @andcor02 
Can you see if the following fixes your problem?
https://github.com/ARMmbed/mbed-os/pull/3053

**Comment by 0xc0170** [comment]
>Can you see if the following fixes your problem?
ARMmbed/mbed-os#3053

Fixed for me with that patch ! Thank you

**Comment by MarceloSalazar** [comment]
Also works for me :)

**Comment by MarceloSalazar** [comment]
We'll close this as soon as mbed-os.lib is updated

**Comment by bulislaw** [comment]
It's updated now, closing.
