### ISSUE TITLE
Wont Compile

### ISSUE THREAD

**Issue by andcor02** [ARMmbed/oob-mbed-os-example-wifi#2]
Using CLI.

command used:  mbed compile -t GCC_ARM -m UBLOX_EVK_ODIN_W2

Upon Compiling for ODIN:

[ERROR] In file included from ./esp8266-driver/ESP8266Interface.cpp:18:0:
./esp8266-driver/ESP8266Interface.h:20:41: fatal error: network-socket/NetworkStack.h: No such file or directory
 #include "network-socket/NetworkStack.h"

**Comment by 0xc0170** [comment]
I can reproduce this issue, we need to update esp8266 reference. I'll test this locally, and send a fix

**Comment by andcor02** [comment]
Fixed
