### ISSUE TITLE
Example should not require editing targets.json

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/oob-mbed-os-example-wifi#3]
The example instructions have to be straightforward and should not require people messing around with mbed OS target's config `mbed-os/targets/targets.json`

These are the expected steps to compile the application:

1. `mbed import mbed-os-example-wifi`   (oob testers will use oob-mbed-os-example-wifi)

2. `cd mbed-os-example-wifi`

3. Configure application. Edit `mbed_app.json`
(see example https://github.com/ARMmbed/oob-mbed-os-example-client/blob/mbed-client-rc/mbed_app.json)

 - Wifi SSID/password credentials
 - Specific ODIN config, e.g. `EMAC`
 - others?

4. Compile for ODIN or other target (with ESP8x shield):
`mbed compile -t ARM -m UBLOX_EVK_ODIN_W2`

@bulislaw @0xc0170

**Comment by 0xc0170** [comment]
Are you referring to this note:

```
UBLOX Odin board (UBLOX_EVK_ODIN_W2) NOTE: WiFi is disabled by default for this board, to enable it you'll need to modify mbed-os/targets/targets.json file and add "EMAC" flag in device_has section for UBLOX_EVK_ODIN_W2 target.
```

This is known limitation for now, will be fixed in the future releases.

**Comment by MarceloSalazar** [comment]
yeap, I expect this to be updated for the release ;-)

**Comment by andreaslarssonublox** [comment]
One alternative to editing target.json might be to add define to command line:
mbed compile -t ARM -m UBLOX_EVK_ODIN_W2 -DDEVICE_EMAC

**Comment by 0xc0170** [comment]
>  mbed compile -t ARM -m UBLOX_EVK_ODIN_W2 -DDEVICE_EMAC

Good tip, I'll send PR to fix the readme, to include this "workaround"

**Comment by MarceloSalazar** [comment]
I don't believe is the the right fix - to be discussed later today.

**Comment by MarceloSalazar** [comment]
Need to add the corresponding configuration in `mbed_app.json` to allow the user to configure ssid/pass for wifi.
@0xc0170 working on this

**Comment by bulislaw** [comment]
Fixed in https://github.com/ARMmbed/oob-mbed-os-example-wifi/pull/7
