### ISSUE TITLE
(docs) Where to connect the antenna on ODIN module?

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/oob-mbed-os-example-wifi#4]
This example is showcasing Wifi on ODIN-W260.

Need a simple comment or picture on where to plug the Wifi antenna on the Odin module.

**Comment by andreaslarssonublox** [comment]
See picture on page 12 here:
https://www.u-blox.com/sites/default/files/ODIN-W2_DataSheet_%28UBX-14039949%29.pdf

It should be the main antenna U.FL connector:
![image](https://cloud.githubusercontent.com/assets/13137551/19436990/92a6a0c2-9473-11e6-9bdd-54e56d3bbcba.png)

**Comment by 0xc0170** [comment]
@ andreaslarssonublox Thank you very much

@MarceloSalazar Where we should specify this? I would propose the platform page.

**Comment by MarceloSalazar** [comment]
> Where we should specify this? I would propose the platform page.

The platform page would be a good place, assuming it's going to be publicly available at the time of the 5.2 release.
We should add a link to such page.

**Comment by 0xc0170** [comment]
> The platform page would be a good place, assuming it's going to be publicly available at the time of the 5.2 release.

+1, can you @MarceloSalazar help or mention here a person that can update it ?

**Comment by MarceloSalazar** [comment]
@screamerbg please point at such page

**Comment by screamerbg** [comment]
@andreaslarssonublox Could you please populate the EVK platform page? I'll send the URL via email shortly

**Comment by 0xc0170** [comment]
@andreaslarssonublox please share with us once the platform  page is update, this should be closed then

**Comment by MarceloSalazar** [comment]
Should be fixed here: https://github.com/ARMmbed/oob-mbed-os-example-wifi/pull/11

**Comment by bulislaw** [comment]
https://github.com/ARMmbed/oob-mbed-os-example-wifi/pull/11 was merged and the OOB repo is merged to the public one. Closing.
